### ISSUE TITLE
Error in submission file

### ISSUE THREAD

**Issue by foolhard** [EGO4D/ego-exo4d-egopose#4]
Hi there, 

I generated a submission file by [inference.py ](https://github.com/EGO4D/ego-exo4d-egopose/blob/main/handpose/models/POTTER/inference.py) and the pretrained model and verified it with dummy test set gt file. 

I tried to submit it to the leaderboard but got an error as below. 

```
Traceback (most recent call last):
  File "/code/scripts/workers/submission_worker.py", line 538, in run_submission
    submission_metadata=submission_serializer.data,
  File "/tmp/tmp2723e64u/compute/challenge_data/challenge_2245/main.py", line 71, in evaluate
    take_name = prediction[take_uid]['take_name']
KeyError: 'take_name'
```

Could you help on this error? 

Regards

**Comment by foolhard** [comment]
My mistake. Submitted to the wrong leaderboard. Should be handpose.
